CREATE TABLE IF NOT EXISTS mpa
(
    id   bigint PRIMARY KEY,
    name varchar NOT NULL
);


CREATE TABLE IF NOT EXISTS genres
(
    id   bigint PRIMARY KEY,
    name varchar NOT NULL
);


CREATE TABLE IF NOT EXISTS films
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar   NOT NULL,
    description  varchar   NOT NULL,
    release_date timestamp NOT NULL,
    duration     bigint    NOT NULL,
    id_mpa       bigint    NOT NULL REFERENCES mpa (id)
);


CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  bigint NOT NULL REFERENCES films (id),
    genre_id bigint NOT NULL REFERENCES genres (id),
    PRIMARY KEY (film_id, genre_id)
);


CREATE TABLE IF NOT EXISTS users
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar,
    email    varchar NOT NULL,
    login    varchar NOT NULL,
    birthday date    NOT NULL
);


CREATE TABLE IF NOT EXISTS friends
(
    user_id   bigint NOT NULL REFERENCES users (id),
    friend_id bigint NOT NULL REFERENCES users (id),
    PRIMARY KEY (user_id, friend_id)
);


CREATE TABLE IF NOT EXISTS liked_by
(
    film_id bigint NOT NULL REFERENCES films (id),
    user_id bigint NOT NULL REFERENCES users (id),
    PRIMARY KEY (film_id, user_id)
);